### ISSUE TITLE
Comparison error at PyVarPortVectorDense `enum_equal(cmd, VarPortCmd.SET)`

### ISSUE THREAD

**Issue by elvinhajizada** [lava-nc/lava#127]
Traceback from the PyVarPortVectorDense, when `cmd` is not an integer, when VarPort has more than 2 dimensions.
@PhilippPlank 
```
Process Process-6:
Traceback (most recent call last):
  File "C:\Users\ehajizad\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\ehajizad\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ehajizad\lava-nc\lava\src\lava\magma\runtime\runtime.py", line 38, in target_fn
    actor.start(*args, **kwargs)
  File "C:\Users\ehajizad\lava-nc\lava\src\lava\magma\core\model\py\model.py", line 62, in start
    self.run()
  File "C:\Users\ehajizad\lava-nc\lava\src\lava\magma\core\model\py\model.py", line 161, in run
    self._handle_var_port(action)
  File "C:\Users\ehajizad\lava-nc\lava\src\lava\magma\core\model\py\model.py", line 245, in _handle_var_port
    var_port.service()
  File "C:\Users\ehajizad\lava-nc\lava\src\lava\magma\core\model\py\ports.py", line 306, in service
    if enum_equal(cmd, VarPortCmd.SET):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Process finished with exit code -1
```

**Comment by PhilippPlank** [comment]
Right, this is a problem with the fixed shape a csp port has. In order to send the data as a whole, I expanded the 1D header to a vector, but forgot about higher dimensions.
