### ISSUE TITLE
Threading gets stuck in runtime and the code is hanging.

### ISSUE THREAD

**Issue by ahmetakman** [lava-nc/lava#236]
Hello,
I am trying to run a process network which is converted via NetX .

Objective of issue:
 When I start to run the network the threads creating ,but it seems some of the messaging do not happen and the network is just hanging. I could not catch any exact problem in debug mode. After waiting quite some time with no response I interrupted the run. The code and the output is given below.

Sincerely,
Ahmet

**Lava version:**

- [ ] **0.4.0** (feature release)
- [ ] **0.3.1** (bug fixes)
- [x] **0.3.0** (current version)
- [ ] **0.2.0**
- [ ] **0.1.2**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request
- [x] documentation request

**Current behavior:**

-  Code is hanging

**Expected behavior:**

- Running the network.

**Steps to reproduce:**

- 

**Related code:**

```
    run_config = CustomRunConfig(select_tag='fixed_pt')
    net.run(condition=RunSteps(num_steps=num_steps), run_cfg=run_config) """This Line"""
    output = output_logger.data.get().flatten()
    gts = gt_logger.data.get().flatten()
    net.stop()

```

**Other information:**

```

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Process SystemProcess-11:
Process SystemProcess-4:
Process SystemProcess-3:
Process SystemProcess-8:
Process SystemProcess-7:
Process SystemProcess-9:
Process SystemProcess-6:
Process SystemProcess-5:
Process SystemProcess-2:
Traceback (most recent call last):
  File "/home/ahmetakman/akman/code/ogam/nmnist/testing2.py", line 129, in <module>
    net.run(condition=RunSteps(num_steps=num_steps), run_cfg=run_config)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/core/process/process.py", line 424, in run
    self._runtime.start(condition)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/runtime.py", line 308, in start
    self._run(run_condition)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/runtime.py", line 326, in _run
    self._get_resp_for_run()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/runtime.py", line 269, in _get_resp_for_run
    data = recv_port.recv()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/compiler/channels/pypychannel.py", line 265, in recv
    self._queue.get()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/compiler/channels/pypychannel.py", line 149, in get
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/message_infrastructure/multiprocessing.py", line 39, in run
    mp.Process.run(self)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/runtime.py", line 91, in target_fn
    actor.start(*args, **kwargs)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/runtime_services/runtime_service.py", line 94, in start
    self.run()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/runtime_services/runtime_service.py", line 348, in run
    self._get_pm_resp()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/runtime_services/runtime_service.py", line 206, in _get_pm_resp
    rcv_msgs.append(ptos_recv_port.recv())
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/compiler/channels/pypychannel.py", line 265, in recv
    self._queue.get()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/compiler/channels/pypychannel.py", line 149, in get
    self.not_empty.wait()
    self.not_empty.wait()
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
  File "/usr/lib/python3.8/threading.py", line 302, in wait
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/message_infrastructure/multiprocessing.py", line 39, in run
    mp.Process.run(self)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/runtime.py", line 91, in target_fn
    actor.start(*args, **kwargs)
    waiter.acquire()
Traceback (most recent call last):
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/message_infrastructure/multiprocessing.py", line 39, in run
    mp.Process.run(self)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/core/model/py/model.py", line 85, in start
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/core/model/py/model.py", line 191, in run
    self._action = self._selector.select(*self._channel_actions)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/runtime.py", line 91, in target_fn
    actor.start(*args, **kwargs)
Traceback (most recent call last):
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/message_infrastructure/multiprocessing.py", line 39, in run
    mp.Process.run(self)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/message_infrastructure/multiprocessing.py", line 39, in run
    mp.Process.run(self)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/runtime.py", line 91, in target_fn
    actor.start(*args, **kwargs)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/compiler/channels/pypychannel.py", line 310, in select
    self._cv.wait()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/core/model/py/model.py", line 85, in start
    self.run()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/core/model/py/model.py", line 85, in start
    self.run()
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/core/model/py/model.py", line 191, in run
    self._action = self._selector.select(*self._channel_actions)
KeyboardInterrupt
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/core/model/py/model.py", line 191, in run
    self._action = self._selector.select(*self._channel_actions)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/compiler/channels/pypychannel.py", line 310, in select
    self._cv.wait()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/compiler/channels/pypychannel.py", line 310, in select
    self._cv.wait()
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
Traceback (most recent call last):
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/message_infrastructure/multiprocessing.py", line 39, in run
    mp.Process.run(self)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/runtime.py", line 91, in target_fn
    actor.start(*args, **kwargs)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/core/model/py/model.py", line 85, in start
    self.run()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/core/model/py/model.py", line 191, in run
    self._action = self._selector.select(*self._channel_actions)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/compiler/channels/pypychannel.py", line 310, in select
    self._cv.wait()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/message_infrastructure/multiprocessing.py", line 39, in run
    mp.Process.run(self)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/runtime.py", line 91, in target_fn
    actor.start(*args, **kwargs)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/core/model/py/model.py", line 85, in start
    self.run()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/core/model/py/model.py", line 191, in run
    self._action = self._selector.select(*self._channel_actions)
KeyboardInterrupt
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/compiler/channels/pypychannel.py", line 310, in select
    self._cv.wait()
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/message_infrastructure/multiprocessing.py", line 39, in run
    mp.Process.run(self)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/runtime.py", line 91, in target_fn
    actor.start(*args, **kwargs)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/message_infrastructure/multiprocessing.py", line 39, in run
    mp.Process.run(self)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/core/model/py/model.py", line 85, in start
    self.run()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/runtime.py", line 91, in target_fn
    actor.start(*args, **kwargs)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/core/model/py/model.py", line 191, in run
    self._action = self._selector.select(*self._channel_actions)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/core/model/py/model.py", line 85, in start
    self.run()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/compiler/channels/pypychannel.py", line 310, in select
    self._cv.wait()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/core/model/py/model.py", line 191, in run
    self._action = self._selector.select(*self._channel_actions)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/compiler/channels/pypychannel.py", line 310, in select
    self._cv.wait()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/runtime/runtime.py", line 91, in target_fn
    actor.start(*args, **kwargs)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/core/model/py/model.py", line 85, in start
    self.run()
KeyboardInterrupt
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/core/model/py/model.py", line 191, in run
    self._action = self._selector.select(*self._channel_actions)
  File "/home/ahmetakman/.local/lib/python3.8/site-packages/lava/magma/compiler/channels/pypychannel.py", line 310, in select
    self._cv.wait()
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by ahmetakman** [comment]
Let me explain from top to bottom what I am doing, so it would be better to detect the problem.

-- Importing the necessary libraries.
-- Converting the network trained by Slayer using NetX 
--Defining the number of samples, steps per sample, and the number of steps.
-- Importing the dataset (which is NMNIST / just like done in the NMNIST training tutorial ).
-- Connecting the loggers and dataset inputs. ( this portion was given [here](https://github.com/lava-nc/lava-dl/issues/53#issuecomment-1075561344), of course, it is corrected with synapse )
-- defined the run config (as Loihi1SimCfg)
-- Tried to run the network by  `    net.run(condition=RunSteps(num_steps=num_steps), run_cfg=run_config)    `
 

That is all. I am getting the error above on the last step. What could be the LAVA's or my error of doing something wrong?




P.S.: I am on the way to getting used to the concept of processes and spiking neuronal networks. So, I am trying to improve. (Done all the tutorials provided, but still, some of the things are vague.)

**Comment by mathisrichter** [comment]
Hi @ahmetakman , thanks for reporting this. I haven't looked into the details you are reporting but could you check this bug report: https://github.com/lava-nc/lava/issues/231? I left some hints for a workaround that may help you in the short term if the issue is the same.

**Comment by ahmetakman** [comment]
Thanks, I looked at your reference. I think they are not related. But I have dug into more low levels and rebuilt the pipeline, it is not hanging right now (working properly). Probably it was about the data loader not feeding the inputs so, it waits. 
I think in lower level lava codes exception handling is a little bit poor. So, the outputs of the errors or tracebacks give almost no information sometimes. I am closing the issue because neither problem nor the solution is detected exactly.
