### ISSUE TITLE
File descriptors seem to remain open after process is stopped (OSError: [Errno 24] Too many open files)

### ISSUE THREAD

**Issue by waltergallegog** [lava-nc/lava#260]
**Objective of issue:** Report strange behavior observed when running and closing processes in a loop. (`OSError: [Errno 24] Too many open files`).

**Lava version:**
- [x] **0.3.1** (bug fixes) (commit fb35fbf2892e)

**I'm submitting a ...** 
- [X] bug report

**Current behavior:**
- When a process is run and then stopped the file descriptors for `dev/shm/psm_xxxxxx` seem to remain open.

**Expected behavior:**
- After a process is stopped, file descriptors should be closed.

**Steps to reproduce:**
I'm performing some tests that consist of the following:
 - In a loop:
    - Instantiate two small processes
    - connect them 
    - call `run()`
    - call `stop()`

I'm using the two processes from `tutorial_05`. One process has a single output, the second has a single input. ProcessA simply sends some data to processB
After using `ulimit -n 4096`, I'm able to set the loop limit to 146. With 147 or larger I get the error: `OSError: [Errno 24] Too many open files).`

With `psutil` I'm monitoring the open files by each process, and by the main. Each of the two processes is opening 14 files (shared mem files, like `/dev/shm/psm_9b4d2e529`), in each iteration. The main is not opening any files.
I noticed that the file descriptors increase in every iteration of the loop, so it seems the file descriptors are not closed after calling stop(), and therefore the fds are not reused, which leads to the `too many open files` error.
Is this the expected behavior?
Is there any other function besides `stop()` that needs to be called to close the `fds` ?

**Related code:**
Here you can find a sample script  to reproduce the issue, and the output of the running script, by running
`python print_fd.py > print_fd_out.txt 2>&1`.
https://github.com/waltergallegog/code-sharing/tree/master/lava/issues

the loop I'm using:
```python
def run_and_stop():
	sender = P1()
	recv   = P2()
	sender.out.connect(recv.inp)
	
	sender.run(RunSteps(num_steps=1), Loihi1SimCfg())
	sender.stop()
	recv  .stop()

def main():
	for _r in range(147):
		run_and_stop()
```

Output from the last two iterations and the error. You can see that by the 146th iteration the fd values are getting close to the limit of 4096

```
PID P2: 302665 [popenfile(path='/media/walter/data/documents/research/tasks/neuro/lava-bm/print_fd_out.txt', fd=1, position=417089, mode='w', flags=32769), popenfile(path='/dev/shm/psm_2c9208ae', fd=4037, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_2c9208ae', fd=4040, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_3df86cab', fd=4041, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_3df86cab', fd=4043, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_eca595e0', fd=4044, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_eca595e0', fd=4045, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_16b51c63', fd=4046, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_16b51c63', fd=4047, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_76df8bc9', fd=4048, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_76df8bc9', fd=4049, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_ca6cb570', fd=4050, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_ca6cb570', fd=4051, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_bf5dd3c1', fd=4052, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_bf5dd3c1', fd=4053, position=0, mode='r+', flags=688130)]
PID P1: 302664 [popenfile(path='/media/walter/data/documents/research/tasks/neuro/lava-bm/print_fd_out.txt', fd=1, position=417089, mode='w', flags=32769), popenfile(path='/dev/shm/psm_2c9208ae', fd=4037, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_2c9208ae', fd=4040, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_3df86cab', fd=4041, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_3df86cab', fd=4043, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_eca595e0', fd=4044, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_eca595e0', fd=4045, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_16b51c63', fd=4046, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_16b51c63', fd=4047, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_76df8bc9', fd=4048, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_76df8bc9', fd=4049, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_ca6cb570', fd=4050, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_ca6cb570', fd=4051, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_bf5dd3c1', fd=4052, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_bf5dd3c1', fd=4053, position=0, mode='r+', flags=688130)]
PID MN: 298727 [popenfile(path='/media/walter/data/documents/research/tasks/neuro/lava-bm/print_fd_out.txt', fd=1, position=419837, mode='w', flags=32769)]

PID P2: 302691 [popenfile(path='/media/walter/data/documents/research/tasks/neuro/lava-bm/print_fd_out.txt', fd=1, position=419994, mode='w', flags=32769), popenfile(path='/dev/shm/psm_308266d4', fd=4065, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_308266d4', fd=4068, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_d0aa39a0', fd=4069, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_d0aa39a0', fd=4071, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_3877efa7', fd=4072, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_3877efa7', fd=4073, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_41374f29', fd=4074, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_41374f29', fd=4075, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_9fb6abe2', fd=4076, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_9fb6abe2', fd=4077, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_03706e87', fd=4078, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_03706e87', fd=4079, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_f72bb9eb', fd=4080, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_f72bb9eb', fd=4081, position=0, mode='r+', flags=688130)]
PID P1: 302692 [popenfile(path='/media/walter/data/documents/research/tasks/neuro/lava-bm/print_fd_out.txt', fd=1, position=419994, mode='w', flags=32769), popenfile(path='/dev/shm/psm_308266d4', fd=4065, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_308266d4', fd=4068, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_d0aa39a0', fd=4069, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_d0aa39a0', fd=4071, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_3877efa7', fd=4072, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_3877efa7', fd=4073, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_41374f29', fd=4074, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_41374f29', fd=4075, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_9fb6abe2', fd=4076, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_9fb6abe2', fd=4077, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_03706e87', fd=4078, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_03706e87', fd=4079, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_f72bb9eb', fd=4080, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/psm_f72bb9eb', fd=4081, position=0, mode='r+', flags=688130)]
PID MN: 298727 [popenfile(path='/media/walter/data/documents/research/tasks/neuro/lava-bm/print_fd_out.txt', fd=1, position=422742, mode='w', flags=32769)]
```

```
Traceback (most recent call last):
  File "/media/walter/data/documents/research/tasks/neuro/lava-bm/src/print_fd.py", line 82, in <module>
    run_loop()
  File "/media/walter/data/documents/research/tasks/neuro/lava-bm/src/print_fd.py", line 77, in run_loop
    run_and_stop()
  File "/media/walter/data/documents/research/tasks/neuro/lava-bm/src/print_fd.py", line 70, in run_and_stop
    sender.run(RunSteps(num_steps=1), Loihi1SimCfg())
  File "/media/walter/data/documents/research/tasks/neuro/lava/src/lava/magma/core/process/process.py", line 422, in run
    self._runtime.initialize()
  File "/media/walter/data/documents/research/tasks/neuro/lava/src/lava/magma/runtime/runtime.py", line 137, in initialize
    self._build_message_infrastructure()
  File "/media/walter/data/documents/research/tasks/neuro/lava/src/lava/magma/runtime/runtime.py", line 163, in _build_message_infrastructure
    self._messaging_infrastructure.start()
  File "/media/walter/data/documents/research/tasks/neuro/lava/src/lava/magma/runtime/message_infrastructure/multiprocessing.py", line 72, in start
    self._smm.start()
  File "/home/walter/miniconda3/envs/lava/lib/python3.10/multiprocessing/managers.py", line 562, in start
    self._process.start()
  File "/home/walter/miniconda3/envs/lava/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/walter/miniconda3/envs/lava/lib/python3.10/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/walter/miniconda3/envs/lava/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/walter/miniconda3/envs/lava/lib/python3.10/multiprocessing/popen_fork.py", line 64, in _launch
    parent_r, child_w = os.pipe()
OSError: [Errno 24] Too many open files
```

**other info**
By contrast, testing a simple open() and close() of different files n a loop results in the same fd being used:
```python
def run_loop():
	fileObjectList = []
	
	for r in range (100000):
		f_name = "file"+str(r)+".txt"
		fileObjectList.append(open(f_name, "w"))
		fd = fileObjectList[r].fileno()
		print("The file descriptor for %s is %s" % (f_name, fd))
		fileObjectList[r].close()
	
if __name__ == '__main__':
	run_loop()
```

```bash
python src/open_close.py 
The file descriptor for file0.txt is 3
The file descriptor for file1.txt is 3
The file descriptor for file2.txt is 3
The file descriptor for file3.txt is 3
The file descriptor for file4.txt is 3
The file descriptor for file5.txt is 3
The file descriptor for file6.txt is 3
The file descriptor for file7.txt is 3
The file descriptor for file8.txt is 3
The file descriptor for file9.txt is 3
...
```

**Comment by joyeshmishra** [comment]
The issue might be happening as we spin up more resources on the OS. Could you increase the ulimit values to even higher values (like 2^16 or 2^20)? You could also set it to unlimited for your experiment session (ulimit -n unlimited) and give it a try. Permanently setting this is not advisable.

**Comment by joyeshmishra** [comment]
Verified on branch: messaging_refactor_release2nd
Commit: fb438ccc16c42bc21cc9c47d37ed74c0f8ae3cc0
Script to check: https://github.com/waltergallegog/code-sharing/tree/master/lava/issues

Last few lines of output which show fd in bounds:

PID P1: 700570 [popenfile(path='/dev/shm/shm1953949094', fd=3, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/shm2073565430', fd=4, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/shm2094176560', fd=5, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/shm130887752', fd=6, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/shm1986645959', fd=7, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/shm1332319413', fd=8, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/shm256146593', fd=9, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/shm606137861', fd=10, position=0, mode='r+', flags=688130)]
PID P2: 700572 [popenfile(path='/dev/shm/shm1953949094', fd=3, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/shm2073565430', fd=4, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/shm2094176560', fd=5, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/shm130887752', fd=6, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/shm1986645959', fd=7, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/shm1332319413', fd=8, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/shm256146593', fd=9, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/shm606137861', fd=10, position=0, mode='r+', flags=688130), popenfile(path='/dev/shm/shm1632095281', fd=11, position=0, mode='r+', flags=688130)]
PID MN: 699674 []

This should make it to the release once the branch is merged and next release happens. Need to use C++ Shmem Implementation.
