### ISSUE TITLE
Memory error after reinitializing and stopping a 2 proccess network multiple times

### ISSUE THREAD

**Issue by GitUser369** [lava-nc/lava#336]
Objective of issue: Allow network to be re-instantiated and run an infinite number of times without memory issues so that lava can be used for off-line training. 

**Lava version:**

- [x] **0.3.0**

**I'm submitting a ...** 

- [ x] bug report

**Current behavior:**

- After reinitializing and running a network about 2000 times I get a memory error. If I am trying to recreate the network with new weights during a training, I wouldn't be able to train for sufficient iterations.

**Expected behavior:**

- I'd expect that we should be able to theoretically reinitialize and run the network an infinite number of times without seeing a memory error. 

**Steps to reproduce:**

- Run the minimal example below.

**Related code:**

```
import numpy as np
from lava.magma.core.run_conditions import RunSteps
from lava.proc.lif.process import LIF
from lava.proc.dense.process import Dense
from lava.magma.core.run_configs import Loihi1SimCfg

num_steps = 5000
du = 10
dv = 100
vth = 4900
if __name__ == "__main__":

    for k in range(num_steps):
        # Create processes
        lif1 = LIF(shape=(3, ),                         
                vth=vth,                             
                dv=dv,                              
                du=du,                              
                bias_mant=(1, 3, 2),           
                name="lif1")

        dense = Dense(weights=np.random.rand(2, 3), shape=(2,3), name='dense')

        lif2 = LIF(shape=(2, ),                        
                vth=vth,                             
                dv=dv,                              
                du=du,                              
                bias_mant=0,                        
                name='lif2')
        
        lif1.s_out.connect(dense.s_in)
        dense.a_out.connect(lif2.a_in)
        
        lif2.run(condition=RunSteps(num_steps=10),
            run_cfg=Loihi1SimCfg(select_tag="fixed_pt"))

        lif2.stop()
        print("k = "+str(k))
```

**Other information:**

1. This particular example is using lava 0.3.0, but I didn't see anything in the code that would indicate that the error wouldn't occur for lava 0.4.0 as well. (I'm using 0.3.0 because it's a dependency for the lava library I'm using.)
2. I noticed that inside of stop() of [runtime.py](https://github.com/lava-nc/lava/blob/main/src/lava/magma/runtime/runtime.py), `self.join()` doesn't appear to be working properly, and the runtime services don't get killed (when I run in debug mode). However if I put `self.join()` immediately below `if self._is_started:`, then the runtime service threads get terminated appropriately. I'm not sure why this is.
3. The fix from 2 allows a few hundred more iterations of the the code before getting a memory issue, but I still see the memory error eventually. 

The output error I'm seeing (before the fix from 2) is:

```
k = 1881
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/resource_tracker.py", line 201, in main
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    cache[rtype].remove(name)
KeyError: '/psm_49e392f1'
    exec(code, run_globals)
  File "/home/jashkanazy-local/dev/sllml/SLLML/src/snn-algos/examples/compare_loihi_to_lava/simple_thread/simple_thread.py", line 78, in <module>
  File "/home/jashkanazy-local/dev/sllml/sllml_venv/lib/python3.8/site-packages/lava/magma/core/process/process.py", line 422, in run
    self._runtime.initialize()
  File "/home/jashkanazy-local/dev/sllml/sllml_venv/lib/python3.8/site-packages/lava/magma/runtime/runtime.py", line 138, in initialize
    self._build_sync_channels()
  File "/home/jashkanazy-local/dev/sllml/sllml_venv/lib/python3.8/site-packages/lava/magma/runtime/runtime.py", line 199, in _build_sync_channels
    channel: Channel = sync_channel_builder.build(
  File "/home/jashkanazy-local/dev/sllml/sllml_venv/lib/python3.8/site-packages/lava/magma/compiler/builders/builder.py", line 747, in build
    return channel_class(
  File "/home/jashkanazy-local/dev/sllml/sllml_venv/lib/python3.8/site-packages/lava/magma/compiler/channels/pypychannel.py", line 337, in __init__
    shm = smm.SharedMemory(int(nbytes * size))
  File "/usr/lib/python3.8/multiprocessing/managers.py", line 1386, in SharedMemory
    sms = shared_memory.SharedMemory(None, create=True, size=size)
  File "/usr/lib/python3.8/multiprocessing/shared_memory.py", line 113, in __init__
    self._mmap = mmap.mmap(self._fd, size)
OSError: [Errno 12] Cannot allocate memory
```

**Comment by PhilippPlank** [comment]
Thank you for reporting this, we need to look into it.

We are currently also working on replacing the multiprocessing library with a more sophisticated solution, which might also help with this problem.

**Comment by joyeshmishra** [comment]
This is a known issue with Python's shared memory implementation leaking file descriptors and eventually OS throwing this error. We are working on a C++ based Shared Memory implementation and a design overall of the message passing architecture keeping the Channel APIs intact (no user code change). That should fix this issue. I don't have a date currently when it will be merged.

**Comment by weidel-p** [comment]
May I add that there was developments in respect of setting weights during runtime. So now you can initialize your network once and set the weights each iteration instead of re-creating the complete network every time. This will speed up execution time drastically and also avoids encountering the Python memory issue.

The script above would look like this:

``` 
import numpy as np
from lava.magma.core.run_conditions import RunSteps
from lava.proc.lif.process import LIF
from lava.proc.dense.process import Dense
from lava.magma.core.run_configs import Loihi1SimCfg

num_steps = 5000
du = 10
dv = 100
vth = 4900
if __name__ == "__main__":
    # Create processes
    lif1 = LIF(shape=(3, ),                         
            vth=vth,                             
            dv=dv,                              
            du=du,                              
            bias_mant=(1, 3, 2),           
            name="lif1")

    dense = Dense(weights=np.random.randint(1, 10, (2, 3)), name='dense')

    lif2 = LIF(shape=(2, ),                        
            vth=vth,                             
            dv=dv,                              
            du=du,                              
            bias_mant=0,                        
            name='lif2')

    lif1.s_out.connect(dense.s_in)
    dense.a_out.connect(lif2.a_in)

    for k in range(num_steps):

        if k > 0:
            dense.weights.set(np.random.randint(1, 10, (2, 3)))        
        
        lif2.run(condition=RunSteps(num_steps=10),
            run_cfg=Loihi1SimCfg(select_tag="fixed_pt"))

        print("k = "+str(k), dense.weights.get())

    lif2.stop()
```

**Comment by JuliaA369** [comment]
Oh nice! Great news! Is this part of main?

**Comment by weidel-p** [comment]
yes

**Comment by JuliaA369** [comment]
Wow, that is a lot faster! And I'm guessing if I was doing a learning connection also reset the traces? Are there any other internal states?

As a future "nice to have" suggestion, it would be nice if the built in Lava processes had a reset() function that automatically reset all the internal states to default values.
