### ISSUE TITLE
Non-deterministic behavior when writing from RefPorts

### ISSUE THREAD

**Issue by mathisrichter** [lava-nc/lava#370]
### User story

As a user, I want RefPorts to behave deterministically when writing to VarPorts.

When writing from a RefPort to a VarPort, the behavior is currently non-deterministic. This shows up in non-deterministically failing  unit tests in `lava/tests/lava/magma/core/process/ports/test_virtual_ports_in_process.py`.

**Steps to reproduce:**

- See unit test attached in the comment below.
- Can also sometimes reproduced by running all tests in `lava/tests/lava/magma/core/process/ports/test_virtual_ports_in_process.py` multiple times (~10-20) on ncl-dev-01.

**Lava version:**
- [x] **0.4.0** (current version)

### Conditions of satisfaction
- Behavior of RefPorts writing to VarPorts should be deterministic.
- Affected unit tests for virtual ports should not fail.

**Comment by mathisrichter** [comment]
This does not seem to be caused by the virtual ports. This unit test also fails sporadically, which just writes from a `RefPort` to a `VarPort`. Upon failure, nothing seems to be written into the `Var` that the `VarPort` points to - it retains its initial values.

```python
# Copyright (C) 2022 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
# See: https://spdx.org/licenses/

import unittest
import numpy as np

from lava.magma.core.decorator import requires, tag, implements
from lava.magma.core.model.py.model import PyLoihiProcessModel
from lava.magma.core.model.py.type import LavaPyType
from lava.magma.core.process.variable import Var
from lava.magma.core.process.process import AbstractProcess
from lava.magma.core.resources import CPU
from lava.magma.core.run_conditions import RunSteps
from lava.magma.core.sync.protocols.loihi_protocol import LoihiProtocol
from lava.magma.core.run_configs import Loihi1SimCfg
from lava.magma.core.model.py.ports import (
    PyInPort,
    PyRefPort,
    PyVarPort
)
from lava.magma.core.process.ports.ports import (
    RefPort,
    VarPort
)


class TestPortsInProcess(unittest.TestCase):
    """Tests PyPorts in Processes."""

    def test_refport_write_to_varport(self) -> None:
        """Tests writing from a RefPort to a VarPort."""
        num_steps = 1
        shape = (4, 3, 2)
        np.random.seed(7739)
        input_data = np.random.randint(256, size=shape)
    
        source = RefPortWriteProcess(data=input_data)
        sink = VarPortProcess(data=np.zeros(shape))

        source.ref_port.connect(sink.var_port)

        try:
            sink.run(condition=RunSteps(num_steps=num_steps),
                     run_cfg=Loihi1SimCfg(select_tag='floating_pt'))
            output = sink.data.get()
        finally:
            sink.stop()

        np.testing.assert_array_equal(output, input_data)


class RefPortWriteProcess(AbstractProcess):
    def __init__(self, data: np.ndarray) -> None:
        super().__init__()
        self.data = Var(shape=data.shape, init=data)
        self.ref_port = RefPort(shape=data.shape)


class VarPortProcess(AbstractProcess):
    def __init__(self, data: np.ndarray) -> None:
        super().__init__()
        self.data = Var(shape=data.shape, init=data)
        self.var_port = VarPort(self.data)


@implements(proc=RefPortWriteProcess, protocol=LoihiProtocol)
@requires(CPU)
@tag('floating_pt')
class PyRefPortWriteProcessModelFloat(PyLoihiProcessModel):
    ref_port: PyRefPort = LavaPyType(PyRefPort.VEC_DENSE, np.int32)
    data: np.ndarray = LavaPyType(np.ndarray, np.int32)

    def post_guard(self):
        return True

    def run_post_mgmt(self):
        self.ref_port.write(self.data)
        self.log.info("Sent output data of RefPortWriteProcess: ",
                      str(self.data))


@implements(proc=VarPortProcess, protocol=LoihiProtocol)
@requires(CPU)
@tag('floating_pt')
class PyVarPortProcessModelFloat(PyLoihiProcessModel):
    var_port: PyInPort = LavaPyType(PyVarPort.VEC_DENSE, np.int32)
    data: np.ndarray = LavaPyType(np.ndarray, np.int32)
```
Failure of this unit test looks as follows
```bash
(.venv) mathisri@ncl-dev-01:~/code/lava-nc/lava/tests/lava/magma/core/process/ports$ python -m unittest test_ports_in_process.py
/home/mathisri/code/lava-nc/frameworks.ai.lava.lava/.venv/lib/python3.8/site-packages/networkx/convert.py:135: ImportWarning: pandas not found, skipping conversion test.
  warnings.warn("pandas not found, skipping conversion test.", ImportWarning)
F
======================================================================
FAIL: test_refport_write_to_varport (test_ports_in_process.TestPortsInProcess)
Tests writing from a RefPort to a VarPort.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mathisri/code/lava-nc/lava/tests/lava/magma/core/process/ports/test_ports_in_process.py", line 50, in test_refport_write_to_varport
    np.testing.assert_array_equal(output, input_data)
  File "/home/mathisri/code/lava-nc/frameworks.ai.lava.lava/.venv/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 934, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "/home/mathisri/code/lava-nc/frameworks.ai.lava.lava/.venv/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

Mismatched elements: 24 / 24 (100%)
Max absolute difference: 237.
Max relative difference: 1.
 x: array([[[0., 0.],
        [0., 0.],
        [0., 0.]],...
 y: array([[[157, 102],
        [165, 187],
        [179, 106]],...

----------------------------------------------------------------------
Ran 1 test in 0.216s

FAILED (failures=1)
```
Here, `x` refers to the variable `input_data` and `y` refers to `output`.

**Comment by joyeshmishra** [comment]
https://github.com/lava-nc/lava/pull/563 - Testing
