### ISSUE TITLE
Get() function doesn't work for  AsyncProtocol

### ISSUE THREAD

**Issue by riccardopignari** [lava-nc/lava#393]
Objective of issue:

**Lava version:**

- [ ] **0.5.0** (feature release)
- [ ] **0.4.1** (bug fixes)
- [x] **0.4.0** (current version)
- [ ] **0.3.0**
- [ ] **0.1.2**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request
- [ ] documentation request

**Current behavior:**

- While trying to retrieve data present in a variable for a process that uses an AsyncProtocol it does not work.

**Expected behavior:**

- Using the get () function the data is returned.

**Steps to reproduce:**

- After creating and running a process, call the get () function for a variable

**Related code:**

```
import numpy as np
from lava.magma.core.decorator import implements, requires
from lava.magma.core.model.py.model import PyAsyncProcessModel
from lava.magma.core.model.py.type import LavaPyType
from lava.magma.core.process.process import AbstractProcess
from lava.magma.core.process.variable import Var
from lava.magma.core.resources import CPU
from lava.magma.core.process.ports.ports import InPort, OutPort
from lava.magma.core.model.py.ports import PyInPort, PyOutPort
from lava.magma.core.run_configs import RunConfig
from lava.magma.core.sync.domain import SyncDomain
from lava.magma.core.sync.protocols.async_protocol import AsyncProtocol
from lava.magma.core.run_conditions import RunSteps


class SimpleProcess(AbstractProcess):
    """Send then Receive process."""

    def __init__(self, shape, send_data):
        super().__init__()
        self.send_port = OutPort(shape=shape)
        self.recv_port = InPort(shape=shape)

        self.send_data = Var(shape=shape, init=send_data)
        self.recv_data = Var(shape=shape, init=np.zeros(shape, dtype=int))


@implements(proc=SimpleProcess, protocol=AsyncProtocol)
@requires(CPU)
class PyModelSendRecv(PyAsyncProcessModel):
    """Class that implements the send then receive model."""
    send_data = LavaPyType(np.ndarray, np.int32)
    recv_data = LavaPyType(np.ndarray, np.int32)

    send_port = LavaPyType(PyOutPort.VEC_DENSE, int, 8)
    recv_port = LavaPyType(PyInPort.VEC_DENSE, int, 8)

    def run_async(self) -> None:
        """Run method that sends data and then waits for incoming data."""
        self.send_port.send(self.send_data)
        self.recv_data = self.recv_port.recv()


class SimpleRunConfig(RunConfig):
    def __init__(self, **kwargs):
        sync_domains = kwargs.pop("sync_domains")
        super().__init__(custom_sync_domains=sync_domains)
        self.model = None
        if "model" in kwargs:
            self.model = kwargs.pop("model")

    def select(self, process, proc_models):
        if self.model is not None:
            if self.model == "sub" and isinstance(process, SimpleProcess):
                return proc_models[1]

        return proc_models[0]


process1 = SimpleProcess(shape=(2, 2), send_data=np.array([[1, 2], [3, 4]]))
process2 = SimpleProcess(shape=(2, 2), send_data=np.array([[5, 6], [7, 8]]))
process1.send_port.connect(process2.recv_port)
process2.send_port.connect(process1.recv_port)

simple_sync_domain = SyncDomain("simple", AsyncProtocol(), [process1, process2])
run_config = SimpleRunConfig(sync_domains=[simple_sync_domain])
process1.run(condition=RunSteps(num_steps=1), run_cfg=run_config)
print(process1.recv_data.get())
process1.stop()

```

**Other information:**

```
Traceback (most recent call last):
  File "/home/user/Scrivania/lava-bm/sandbox_async.py", line 68, in <module>
    print(process1.recv_data.get())
  File "/home/user/Scrivania/lava-bm/venv/src/lava/src/lava/magma/core/process/variable.py", line 141, in get
    return self.process.runtime.get_var(self.id, idx)
  File "/home/user/Scrivania/lava-bm/venv/src/lava/src/lava/magma/runtime/runtime.py", line 479, in get_var
    buffer = buffer.reshape(ev.shape)
ValueError: cannot reshape array of size 0 into shape (2,2)
```

**Comment by ysingh7** [comment]
Async Protocol cannot support get. Since the process doesn't have any phase (pre-determined checkpoints), there is no way of knowing what time data can be read. Only way of reading/writing is via Ports.
